# Fix the function
# I created this function to add five to any number that was passed in to it and 
# return the new value. It doesn't throw any errors but it returns the wrong number.

# def add_five(num):
#     total = num + 5
#     return num

# Can you help me fix the function?
